### ISSUE TITLE
Material UI Not Showing Up in Preferences after Installed - WebStorm 2022.1

### ISSUE THREAD

**Issue by dschinkel** [mallowigi/material-theme-ui-lite#98]
**Look bro:**

I woke up to your snarky reply this morning.  And it didn't put me in a good mood.  

1) I will put in a bad review if this thing plain out doesn't work.  Don't tell people not to put bad reviews, that's their choice. Stop bitching
2) You expect us to know about your repo? put the damn link in the details (and make it obvious we are to go there for support) in the **JetBrains marketplace page for this plugin**.  I don't automatically hunt around for repos when I land on the JetBrains Marketplace

The BUG: https://ibb.co/dB144cy

**Same thing in IntelliJ Ultimate 2022.1** Build #IU-221.5080.210:

<img width="1381" alt="Screen Shot 2022-04-23 at 8 51 44 AM" src="https://user-images.githubusercontent.com/338798/164908836-f49b5cae-2a3b-4bb0-8a75-78749b05c3c7.png">

I uninstalled and reinstalled the plugin, still no go.

https://plugins.jetbrains.com/plugin/8006-material-theme-ui/reviews#review=67128
```
I see nothing now in Webstorm in preferences; where the hell is it? It's always there after you install the plugin so wtf is going on lately?

https://ibb.co/dB144cy

WebStorm 2022.1
```

```
[Elior Boukhobza](https://plugins.jetbrains.com/author/d610d835-d13b-4884-9cb5-cf993322b20b)
 (vendor)
Today
I don't see any problems here: https://cln.sh/c4KTPA

Also please don't use this form to report bugs (let alone giving bad reviews), there's GitHub for that.]]
```

**Comment by mallowigi** [comment]
1. You're using Material Theme Lite and yet you complain about the Material Theme plugin. If there's a bug in the Lite version, I would have been able to reproduce, and all this discussion wouldn't have happened.
2. Whenever you try to put a bad review, JetBrains itself is asking you to think carefully and check whether you should post an issue in the repo rather than complaining first hand. There are links to the repos everywhere, why such dishonesty?
3. I answered you that I can't reproduce, and you call it a "snarky comment". And yet, I'm the one "bitching"? I concur that this was not a friendly tone, I am almost 100% sure that I would have answered differently if there wasn't that 1-star involved.
4. Sorry I'm bad at marketing. That's not my job. Nor doing these plugins as well, it's a hobby of mine, period. Sorry if I offended you, but you have to put yourself in my shoes. You said you read my answers and don't like my tone. That's fine, again, I'm not a sales rep. But as a fellow developer you should be able to see that a lot of these reviews are what you called them: "bitching". People discontent with the paid status of the plugin calling me a greedy bastard and expecting me to work for them for free. Sorry if I'm not giving the other cheek. 
5. Also people removing bad reviews? I don't believe that. It's so easy to give bad reviews, I did that in the past as well when I was discontent. Only now that I'm a vendor as well I understand that that was an ass move. I'm not blaming that, I've just learned to live with it.

I'm leaving this open for transparency, not trying to censor my behavior nor what I'm thinking. Again, I'm not a sales rep, I'm a (too?) honest developer trying to make a buck. Sorry if I put you on the wrong foot, but try to be sympathetic next time.

**Comment by dschinkel** [comment]
>People discontent with the paid status of the plugin calling me a greedy bastard and expecting me to work for them for free

Well I'm not asking for that, those people are jerks, agree.

**Comment by mallowigi** [comment]
And that was the case, I was saying "sorry, I don't see what is the problem here". I would have done this as well if it were in the repo, and then after investigation I would have came to the conclusion that it was the wrong plugin to begin with. But since it was on a review forum that wasn't the place to talk about this at all, so I redirected you to the repo. What's wrong with that?

I'm reopening because this is the repo for the lite version and there is an issue there, not going to deny that.

**Comment by dschinkel** [comment]
And Yes, I did remove my one star review.  Some people do do that if they get decent replies.

**Comment by mallowigi** [comment]
That reply was decent? Ok I'm now confused... I guess I REALLY am bad at marketing...

Anyway thanks for sympathizing... It's really uncommon.

Regarding the issue, I'm seldom updating this plugin, but I'll do every now and then. Thanks for reporting.

**Comment by dschinkel** [comment]
No I removed my reply because you were humble about it.  And I also get annoyed at our profession who expects free handouts for everything (free free free)

I was in a bad mood also, so I probably went a little overboard myself. Thanks for looking into this.

**Comment by dschinkel** [comment]
To show my support I went with a monthly subscription.

**Comment by mallowigi** [comment]
Confused more and more 😅
